site_name: DAOstack Arc.js Documentation
repo_url: https://github.com/daostack/arc.js/
repo_name: daostack/arc.js
site_description: A JavaScript library for interacting with @daostack/arc ethereum smart contracts
docs_dir: docs
extra_templates:
- index.html
markdown_extensions:
- admonition
- codehilite:
    linenums: true
- toc:
    permalink: true
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'amber'
extra:
  social:
  - type: 'github'
    link: 'https://github.com/daostack/arc.js'
  - type: 'slack'
    link: 'https://daostack.slack.com'
  - type: 'telegram'
    link: 'https://t.me/daostackcommunity'

pages:
- 'Overview': Home.md
- 'Configuration': 'Configuration.md'
- 'DAOs': 'CreateDao.md'
- 'Schemes': 'Schemes.md'
- 'Proposals': 'Proposals.md'
- 'Global Constraints': 'GCs.md'
- 'Contract Migration': 'Migration.md'
- 'Using GanacheDb': 'GanacheDb.md'
- 'API Reference': 
  - Index : "api/README.md"
  - AbsoluteVoteWrapper : 'api/classes/AbsoluteVoteWrapper.md'
  - ArcTransactionAgreementResult : 'api/classes/ArcTransactionAgreementResult.md'
  - ArcTransactionDataResult : 'api/classes/ArcTransactionDataResult.md'
  - ArcTransactionProposalResult : 'api/classes/ArcTransactionProposalResult.md'
  - ArcTransactionResult : 'api/classes/ArcTransactionResult.md'
  - AvatarService : 'api/classes/AvatarService.md'
  - Config : 'api/classes/Config.md'
  - ConsoleLogger : 'api/classes/ConsoleLogger.md'
  - Contracts : 'api/classes/Contracts.md'
  - ContractWrapperFactory : 'api/classes/ContractWrapperFactory.md'
  - ContributionRewardWrapper : 'api/classes/ContributionRewardWrapper.md'
  - DAO : 'api/classes/DAO.md'
  - DaoCreatorWrapper : 'api/classes/DaoCreatorWrapper.md'
  - ExtendTruffleContract : 'api/classes/ExtendTruffleContract.md'
  - GenesisProtocolWrapper : 'api/classes/GenesisProtocolWrapper.md'
  - GlobalConstraintRegistrarWrapper : 'api/classes/GlobalConstraintRegistrarWrapper.md'
  - LoggingService : 'api/classes/LoggingService.md'
  - SchemeRegistrarWrapper : 'api/classes/SchemeRegistrarWrapper.md'
  - TokenCapGCWrapper : 'api/classes/TokenCapGCWrapper.md'
  - UpgradeSchemeWrapper : 'api/classes/UpgradeSchemeWrapper.md'
  - Utils : 'api/classes/Utils.md'
  - VestingSchemeWrapper : 'api/classes/VestingSchemeWrapper.md'
  - VoteInOrganizationSchemeWrapper : 'api/classes/VoteInOrganizationSchemeWrapper.md'
  - BinaryVoteResult : 'api/enums/BinaryVoteResult.md'
  - DefaultSchemePermissions : 'api/enums/DefaultSchemePermissions.md'
  - ExecutionState : 'api/enums/ExecutionState.md'
  - LogLevel : 'api/enums/LogLevel.md'
  - RewardType : 'api/enums/RewardType.md'
  - SchemePermissions : 'api/enums/SchemePermissions.md'
  - AbsoluteVoteParams : 'api/interfaces/AbsoluteVoteParams.md'
  - Agreement : 'api/interfaces/Agreement.md'
  - AgreementCancelEventResult : 'api/interfaces/AgreementCancelEventResult.md'
  - AgreementProposalEventResult : 'api/interfaces/AgreementProposalEventResult.md'
  - ArcContractInfo : 'api/interfaces/ArcContractInfo.md'
  - ArcDeployedContractNames : 'api/interfaces/ArcDeployedContractNames.md'
  - ArcDeployedContracts : 'api/interfaces/ArcDeployedContracts.md'
  - CancelProposalEventResult : 'api/interfaces/CancelProposalEventResult.md'
  - CancelVotingEventResult : 'api/interfaces/CancelVotingEventResult.md'
  - ChangeUpgradeSchemeProposalEventResult : 'api/interfaces/ChangeUpgradeSchemeProposalEventResult.md'
  - CollectEventResult : 'api/interfaces/CollectEventResult.md'
  - CollectVestingAgreementConfig : 'api/interfaces/CollectVestingAgreementConfig.md'
  - CommonVestingAgreementConfig : 'api/interfaces/CommonVestingAgreementConfig.md'
  - ContributionProposal : 'api/interfaces/ContributionProposal.md'
  - ContributionRewardParams : 'api/interfaces/ContributionRewardParams.md'
  - ContributionRewardParamsReturn : 'api/interfaces/ContributionRewardParamsReturn.md'
  - ContributionRewardRedeemParams : 'api/interfaces/ContributionRewardRedeemParams.md'
  - ContributionRewardSpecifiedRedemptionParams : 'api/interfaces/ContributionRewardSpecifiedRedemptionParams.md'
  - ControllerAddGlobalConstraintsEventLogEntry : 'api/interfaces/ControllerAddGlobalConstraintsEventLogEntry.md'
  - ControllerRegisterSchemeEventLogEntry : 'api/interfaces/ControllerRegisterSchemeEventLogEntry.md'
  - CreateVestingAgreementConfig : 'api/interfaces/CreateVestingAgreementConfig.md'
  - DaoGlobalConstraintInfo : 'api/interfaces/DaoGlobalConstraintInfo.md'
  - DaoSchemeInfo : 'api/interfaces/DaoSchemeInfo.md'
  - DecodedLogEntry : 'api/interfaces/DecodedLogEntry.md'
  - DecodedLogEntryEvent : 'api/interfaces/DecodedLogEntryEvent.md'
  - EventFetcher : 'api/interfaces/EventFetcher.md'
  - ExecutableInterface : 'api/interfaces/ExecutableInterface.md'
  - ExecutedGenesisProposal : 'api/interfaces/ExecutedGenesisProposal.md'
  - ExecuteProposalEventResult : 'api/interfaces/ExecuteProposalEventResult.md'
  - FilterObject : 'api/interfaces/FilterObject.md'
  - ForgeOrgConfig : 'api/interfaces/ForgeOrgConfig.md'
  - FounderConfig : 'api/interfaces/FounderConfig.md'
  - GenesisProtocolExecuteProposalEventResult : 'api/interfaces/GenesisProtocolExecuteProposalEventResult.md'
  - GenesisProtocolParams : 'api/interfaces/GenesisProtocolParams.md'
  - GetAgreementParams : 'api/interfaces/GetAgreementParams.md'
  - GetBeneficiaryRewardsParams : 'api/interfaces/GetBeneficiaryRewardsParams.md'
  - GetDaoProposalsConfig : 'api/interfaces/GetDaoProposalsConfig.md'
  - GetNumberOfChoicesConfig : 'api/interfaces/GetNumberOfChoicesConfig.md'
  - GetProposalAvatarConfig : 'api/interfaces/GetProposalAvatarConfig.md'
  - GetProposalStatusConfig : 'api/interfaces/GetProposalStatusConfig.md'
  - GetProposalStatusResult : 'api/interfaces/GetProposalStatusResult.md'
  - GetRedeemableReputationProposerConfig : 'api/interfaces/GetRedeemableReputationProposerConfig.md'
  - GetRedeemableReputationStakerConfig : 'api/interfaces/GetRedeemableReputationStakerConfig.md'
  - GetRedeemableReputationVoterConfig : 'api/interfaces/GetRedeemableReputationVoterConfig.md'
  - GetRedeemableTokensStakerConfig : 'api/interfaces/GetRedeemableTokensStakerConfig.md'
  - GetRedeemableTokensVoterConfig : 'api/interfaces/GetRedeemableTokensVoterConfig.md'
  - GetScoreConfig : 'api/interfaces/GetScoreConfig.md'
  - GetScoreThresholdParamsConfig : 'api/interfaces/GetScoreThresholdParamsConfig.md'
  - GetScoreThresholdParamsResult : 'api/interfaces/GetScoreThresholdParamsResult.md'
  - GetStakerInfoConfig : 'api/interfaces/GetStakerInfoConfig.md'
  - GetStakerInfoResult : 'api/interfaces/GetStakerInfoResult.md'
  - GetStateConfig : 'api/interfaces/GetStateConfig.md'
  - GetThresholdConfig : 'api/interfaces/GetThresholdConfig.md'
  - GetTotalReputationSupplyConfig : 'api/interfaces/GetTotalReputationSupplyConfig.md'
  - GetVoterInfoConfig : 'api/interfaces/GetVoterInfoConfig.md'
  - GetVoterInfoResult : 'api/interfaces/GetVoterInfoResult.md'
  - GetVoteStakeConfig : 'api/interfaces/GetVoteStakeConfig.md'
  - GetVoteStatusConfig : 'api/interfaces/GetVoteStatusConfig.md'
  - GetWinningVoteConfig : 'api/interfaces/GetWinningVoteConfig.md'
  - ILogger : 'api/interfaces/ILogger.md'
  - InitialSchemesSetEventResult : 'api/interfaces/InitialSchemesSetEventResult.md'
  - IsVotableConfig : 'api/interfaces/IsVotableConfig.md'
  - LogEntry : 'api/interfaces/LogEntry.md'
  - LogEntryEvent : 'api/interfaces/LogEntryEvent.md'
  - NewContributionProposalEventResult : 'api/interfaces/NewContributionProposalEventResult.md'
  - NewDaoConfig : 'api/interfaces/NewDaoConfig.md'
  - NewDaoVotingMachineConfig : 'api/interfaces/NewDaoVotingMachineConfig.md'
  - NewGlobalConstraintsProposalEventResult : 'api/interfaces/NewGlobalConstraintsProposalEventResult.md'
  - NewOrgEventResult : 'api/interfaces/NewOrgEventResult.md'
  - NewProposalEventResult : 'api/interfaces/NewProposalEventResult.md'
  - NewSchemeProposalEventResult : 'api/interfaces/NewSchemeProposalEventResult.md'
  - NewUpgradeProposalEventResult : 'api/interfaces/NewUpgradeProposalEventResult.md'
  - NewVestedAgreementEventResult : 'api/interfaces/NewVestedAgreementEventResult.md'
  - ProposalDeletedEventResult : 'api/interfaces/ProposalDeletedEventResult.md'
  - ProposalExecutedEventResult : 'api/interfaces/ProposalExecutedEventResult.md'
  - ProposalRewards : 'api/interfaces/ProposalRewards.md'
  - ProposeContributionRewardParams : 'api/interfaces/ProposeContributionRewardParams.md'
  - ProposeControllerParams : 'api/interfaces/ProposeControllerParams.md'
  - ProposeToAddModifyGlobalConstraintParams : 'api/interfaces/ProposeToAddModifyGlobalConstraintParams.md'
  - ProposeToAddModifySchemeParams : 'api/interfaces/ProposeToAddModifySchemeParams.md'
  - ProposeToRemoveGlobalConstraintParams : 'api/interfaces/ProposeToRemoveGlobalConstraintParams.md'
  - ProposeToRemoveSchemeParams : 'api/interfaces/ProposeToRemoveSchemeParams.md'
  - ProposeUpgradingSchemeParams : 'api/interfaces/ProposeUpgradingSchemeParams.md'
  - ProposeVestingAgreementConfig : 'api/interfaces/ProposeVestingAgreementConfig.md'
  - ProposeVoteConfig : 'api/interfaces/ProposeVoteConfig.md'
  - RedeemConfig : 'api/interfaces/RedeemConfig.md'
  - RedeemEtherEventResult : 'api/interfaces/RedeemEtherEventResult.md'
  - RedeemEventResult : 'api/interfaces/RedeemEventResult.md'
  - RedeemExternalTokenEventResult : 'api/interfaces/RedeemExternalTokenEventResult.md'
  - RedeemNativeTokenEventResult : 'api/interfaces/RedeemNativeTokenEventResult.md'
  - RedeemReputationEventResult : 'api/interfaces/RedeemReputationEventResult.md'
  - RemoveGlobalConstraintsProposalEventResult : 'api/interfaces/RemoveGlobalConstraintsProposalEventResult.md'
  - RemoveSchemeProposalEventResult : 'api/interfaces/RemoveSchemeProposalEventResult.md'
  - RevokeSignToCancelAgreementEventResult : 'api/interfaces/RevokeSignToCancelAgreementEventResult.md'
  - RevokeSignToCancelVestingAgreementConfig : 'api/interfaces/RevokeSignToCancelVestingAgreementConfig.md'
  - SchemeConfig : 'api/interfaces/SchemeConfig.md'
  - SchemesConfig : 'api/interfaces/SchemesConfig.md'
  - SetSchemesConfig : 'api/interfaces/SetSchemesConfig.md'
  - ShouldBoostConfig : 'api/interfaces/ShouldBoostConfig.md'
  - SignToCancelAgreementEventResult : 'api/interfaces/SignToCancelAgreementEventResult.md'
  - SignToCancelVestingAgreementConfig : 'api/interfaces/SignToCancelVestingAgreementConfig.md'
  - StakeConfig : 'api/interfaces/StakeConfig.md'
  - StakeEventResult : 'api/interfaces/StakeEventResult.md'
  - StandardSchemeParams : 'api/interfaces/StandardSchemeParams.md'
  - TokenCapGcParams : 'api/interfaces/TokenCapGcParams.md'
  - TransactionReceipt : 'api/interfaces/TransactionReceipt.md'
  - TransactionReceiptTruffle : 'api/interfaces/TransactionReceiptTruffle.md'
  - VoteConfig : 'api/interfaces/VoteConfig.md'
  - VoteInOrganizationProposeVoteConfig : 'api/interfaces/VoteInOrganizationProposeVoteConfig.md'
  - VoteOnBehalfEventResult : 'api/interfaces/VoteOnBehalfEventResult.md'
  - VoteProposalEventResult : 'api/interfaces/VoteProposalEventResult.md'
  - VoteWithSpecifiedAmountsConfig : 'api/interfaces/VoteWithSpecifiedAmountsConfig.md'
